### ISSUE TITLE
sox is no longer available under this channel i get this error

### ISSUE THREAD

**Issue by kunalsharmagnome** [conda-forge/sox-feedstock#17]
Issue: sox in no longer available under this channel conda-forge

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>
![image](https://user-images.githubusercontent.com/11546854/47553043-ab8c9500-d923-11e8-86a8-0cc9df159603.png)

**Comment by ocefpaf** [comment]
Your `conda list` and `conda info` are empty and the attached image seems to be broken :-/

Based on the fact that you attached an image I'm guessing you are trying to install `sox` on Windows. If so, we never had a Windows package.

Here are the Linux and OS X versions available:

https://anaconda.org/conda-forge/sox/files
